source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitlab.atino.net/appls/atinopodspecrepo.git'

use_frameworks!
platform :ios, '8.0'

abstract_target 'JBPersistenceStore' do
    
    pod 'JBPersistenceStore-Protocols'
    pod 'JBPersistenceStore', :path => '../'
    pod 'YapDatabase'
    
    target 'JBPersistenceStore_Example' do
    end
    
    target 'JBPersistenceStore_Tests' do
    end
end
